extern void override_options PARAMS((void));
extern rtx function_arg PARAMS(( CUMULATIVE_ARGS *,enum machine_mode,tree,int ));
extern int const_costs PARAMS(());
extern void print_operand PARAMS(());
extern void print_operand_address PARAMS(());
extern void final_prescan_insn PARAMS((rtx insn,rtx *,int ));
extern char * output_move_single PARAMS(());
extern char * output_move_double PARAMS(( rtx * ));
extern char * output_btst PARAMS(( rtx * ));
extern char * output_bclr PARAMS(( rtx * ));
extern char * output_bset PARAMS(( rtx * ));
extern int call_address_operand PARAMS(( rtx,enum machine_mode ));
extern int power_of_two_operand PARAMS(());
extern int not_power_of_two_operand PARAMS(());
extern int general_operand_post_inc PARAMS(( rtx,enum machine_mode ));
extern int compute_register_save_size PARAMS(( long * ));
extern int compute_frame_size PARAMS(());
extern void expand_prologue PARAMS(());
extern void expand_epilogue PARAMS(());
extern void notice_update_cc PARAMS(());
extern c33_data_area c33_get_data_area PARAMS(( tree ));
extern void c33_encode_data_area PARAMS(( tree )); 
extern int c33_interrupt_function_p PARAMS((void));
extern void c33_select_section PARAMS(( tree,int ));
extern int nshift_operator PARAMS(( rtx,enum machine_mode ));
extern int expand_a_shift PARAMS(( enum machine_mode,int,rtx* ));
extern char * emit_a_shift PARAMS(( enum rtx_code,rtx * ));
extern void print_options PARAMS(( FILE * ));
extern void declare_object PARAMS(());
extern void c33_output_aligned_bss PARAMS(( FILE *,tree,char*,int,int ));
extern void c33_output_common PARAMS(( FILE *,tree,char *,int,int ));
extern void c33_output_local PARAMS(( FILE *,tree,char *,int,int ));
extern void asm_file_start PARAMS(( FILE * ));
extern void expand_block_move PARAMS(( rtx* ));
extern char * output_block_move PARAMS(( rtx,rtx*,int ));
extern int c33_adjust_insn_length PARAMS(( rtx,int ));
