WIKIREADER_ROOT = $(WRDK_SHARE)/../..

HOST_TOOLS := $(WIKIREADER_ROOT)/host-tools
SAMO_LIB := $(WIKIREADER_ROOT)/samo-lib

GRIFO = ${SAMO_LIB}/grifo
GRIFO_SCRIPTS = $(GRIFO)/scripts

IMAGE2HEADER = $(HOST_TOOLS)/imagetool/image2header
XPM2ICON = $(GRIFO_SCRIPTS)/xpm2icon


